#!/bin/sh
rm -Rf "/Library/Audio/Plug-Ins/VST/Mverb2020.vst"
rm -Rf "/Library/Audio/Plug-Ins/VST3/Mverb2020.vst3"
rm -Rf "/Library/Audio/Plug-Ins/Components/Mverb2020.component"
rm -Rf "/Library/Audio/Plug-Ins/CLAP/Mverb2020.clap"
rm -Rf "/Library/Audio/Presets/SocaLabs/Mverb2020/Presets"
exit 0
